"""sprint 3: empresas + facts + promesas + transacciones + menciones

Revision ID: 11c6c96cd8c0
Revises: 6cdb5bcf75e8
Create Date: 2026-05-11 23:47:45.255300

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11c6c96cd8c0'
down_revision: str | None = '6cdb5bcf75e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_canonico', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('seguir', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_canonico'),
    schema='core'
    )
    op.create_index('ix_core_empresas_seguir', 'empresas', ['seguir'], unique=False, schema='core')
    op.create_table('facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('fecha_referida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confianza', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['core.items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['core.personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_core_facts_item_id', 'facts', ['item_id'], unique=False, schema='core')
    op.create_index('ix_core_facts_persona_id', 'facts', ['persona_id'], unique=False, schema='core')
    op.create_table('menciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nombre_raw', sa.String(length=255), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('resuelto', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['core.empresas.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['core.items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['core.personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_core_menciones_empresa_id', 'menciones', ['empresa_id'], unique=False, schema='core')
    op.create_index('ix_core_menciones_item_id', 'menciones', ['item_id'], unique=False, schema='core')
    op.create_index('ix_core_menciones_persona_id', 'menciones', ['persona_id'], unique=False, schema='core')
    op.create_table('promesas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('es_de_damian', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('plazo_texto', sa.String(length=255), nullable=True),
    sa.Column('plazo_fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='pendiente', nullable=False),
    sa.Column('confianza', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['core.items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['core.personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_core_promesas_estado', 'promesas', ['estado'], unique=False, schema='core')
    op.create_index('ix_core_promesas_item_id', 'promesas', ['item_id'], unique=False, schema='core')
    op.create_index('ix_core_promesas_persona_id', 'promesas', ['persona_id'], unique=False, schema='core')
    op.create_table('transacciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monto_raw', sa.String(length=100), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('concepto', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confianza', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['core.items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['core.personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_core_transacciones_fecha', 'transacciones', ['fecha'], unique=False, schema='core')
    op.create_index('ix_core_transacciones_item_id', 'transacciones', ['item_id'], unique=False, schema='core')
    op.create_index('ix_core_transacciones_persona_id', 'transacciones', ['persona_id'], unique=False, schema='core')
    op.create_index('ix_core_transacciones_tipo', 'transacciones', ['tipo'], unique=False, schema='core')
    op.drop_constraint(op.f('items_persona_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'personas', ['persona_id'], ['id'], source_schema='core', referent_schema='core')
    op.drop_constraint(op.f('attachments_item_id_fkey'), 'attachments', schema='media', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'items', ['item_id'], ['id'], source_schema='media', referent_schema='core')
    op.drop_constraint(op.f('jobs_item_id_fkey'), 'jobs', schema='processing', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'items', ['item_id'], ['id'], source_schema='processing', referent_schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', schema='processing', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_item_id_fkey'), 'jobs', 'items', ['item_id'], ['id'], source_schema='processing')
    op.drop_constraint(None, 'attachments', schema='media', type_='foreignkey')
    op.create_foreign_key(op.f('attachments_item_id_fkey'), 'attachments', 'items', ['item_id'], ['id'], source_schema='media')
    op.drop_constraint(None, 'items', schema='core', type_='foreignkey')
    op.create_foreign_key(op.f('items_persona_id_fkey'), 'items', 'personas', ['persona_id'], ['id'])
    op.drop_index('ix_core_transacciones_tipo', table_name='transacciones', schema='core')
    op.drop_index('ix_core_transacciones_persona_id', table_name='transacciones', schema='core')
    op.drop_index('ix_core_transacciones_item_id', table_name='transacciones', schema='core')
    op.drop_index('ix_core_transacciones_fecha', table_name='transacciones', schema='core')
    op.drop_table('transacciones', schema='core')
    op.drop_index('ix_core_promesas_persona_id', table_name='promesas', schema='core')
    op.drop_index('ix_core_promesas_item_id', table_name='promesas', schema='core')
    op.drop_index('ix_core_promesas_estado', table_name='promesas', schema='core')
    op.drop_table('promesas', schema='core')
    op.drop_index('ix_core_menciones_persona_id', table_name='menciones', schema='core')
    op.drop_index('ix_core_menciones_item_id', table_name='menciones', schema='core')
    op.drop_index('ix_core_menciones_empresa_id', table_name='menciones', schema='core')
    op.drop_table('menciones', schema='core')
    op.drop_index('ix_core_facts_persona_id', table_name='facts', schema='core')
    op.drop_index('ix_core_facts_item_id', table_name='facts', schema='core')
    op.drop_table('facts', schema='core')
    op.drop_index('ix_core_empresas_seguir', table_name='empresas', schema='core')
    op.drop_table('empresas', schema='core')
    # ### end Alembic commands ###
