"""sprint 2.5: personas.seguir + core.conversaciones

Revision ID: 580e06d66386
Revises: a88a6d0e567b
Create Date: 2026-05-11 18:59:13.381460

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '580e06d66386'
down_revision: str | None = 'a88a6d0e567b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nombre_display', sa.String(length=255), nullable=False),
    sa.Column('seguir', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id'),
    schema='core'
    )
    op.create_index('ix_core_conversaciones_tipo_seguir', 'conversaciones', ['tipo', 'seguir'], unique=False, schema='core')
    op.drop_constraint(op.f('items_persona_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'personas', ['persona_id'], ['id'], source_schema='core', referent_schema='core')
    op.add_column('personas', sa.Column('seguir', sa.Boolean(), server_default='true', nullable=False))
    op.drop_constraint(op.f('attachments_item_id_fkey'), 'attachments', schema='media', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'items', ['item_id'], ['id'], source_schema='media', referent_schema='core')
    op.drop_constraint(op.f('jobs_item_id_fkey'), 'jobs', schema='processing', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'items', ['item_id'], ['id'], source_schema='processing', referent_schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', schema='processing', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_item_id_fkey'), 'jobs', 'items', ['item_id'], ['id'], source_schema='processing')
    op.drop_constraint(None, 'attachments', schema='media', type_='foreignkey')
    op.create_foreign_key(op.f('attachments_item_id_fkey'), 'attachments', 'items', ['item_id'], ['id'], source_schema='media')
    op.drop_column('personas', 'seguir')
    op.drop_constraint(None, 'items', schema='core', type_='foreignkey')
    op.create_foreign_key(op.f('items_persona_id_fkey'), 'items', 'personas', ['persona_id'], ['id'])
    op.drop_index('ix_core_conversaciones_tipo_seguir', table_name='conversaciones', schema='core')
    op.drop_table('conversaciones', schema='core')
    # ### end Alembic commands ###
