"""sprint1: schema base

Revision ID: a88a6d0e567b
Revises: 
Create Date: 2026-05-09 16:26:47.140935

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a88a6d0e567b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_canonico', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_canonico'),
    schema='core'
    )
    op.create_index('ix_core_personas_email', 'personas', ['email'], unique=False, schema='core')
    op.create_index('ix_core_personas_telefono', 'personas', ['telefono'], unique=False, schema='core')
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direccion', sa.String(length=20), nullable=False),
    sa.Column('es_media', sa.Boolean(), nullable=False),
    sa.Column('media_tipo', sa.String(length=30), nullable=True),
    sa.Column('nivel_procesamiento', sa.Integer(), nullable=False),
    sa.Column('tono', sa.String(length=50), nullable=True),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['core.personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_core_items_fecha', 'items', ['fecha'], unique=False, schema='core')
    op.create_index('ix_core_items_persona_id', 'items', ['persona_id'], unique=False, schema='core')
    op.create_index('ix_core_items_source_conversation', 'items', ['source', 'conversation_id'], unique=False, schema='core')
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('filename_original', sa.String(length=500), nullable=True),
    sa.Column('minio_path', sa.String(length=1000), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamanio_bytes', sa.Integer(), nullable=True),
    sa.Column('procesado', sa.Boolean(), nullable=False),
    sa.Column('nivel_procesamiento', sa.Integer(), nullable=False),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['core.items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='media'
    )
    op.create_index('ix_media_attachments_item_id', 'attachments', ['item_id'], unique=False, schema='media')
    op.create_index('ix_media_attachments_sha256', 'attachments', ['sha256'], unique=False, schema='media')
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('parametros', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('max_intentos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['core.items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='processing'
    )
    op.create_index('ix_processing_jobs_estado', 'jobs', ['estado'], unique=False, schema='processing')
    op.create_index('ix_processing_jobs_item_id', 'jobs', ['item_id'], unique=False, schema='processing')
    op.create_index('ix_processing_jobs_tipo', 'jobs', ['tipo'], unique=False, schema='processing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processing_jobs_tipo', table_name='jobs', schema='processing')
    op.drop_index('ix_processing_jobs_item_id', table_name='jobs', schema='processing')
    op.drop_index('ix_processing_jobs_estado', table_name='jobs', schema='processing')
    op.drop_table('jobs', schema='processing')
    op.drop_index('ix_media_attachments_sha256', table_name='attachments', schema='media')
    op.drop_index('ix_media_attachments_item_id', table_name='attachments', schema='media')
    op.drop_table('attachments', schema='media')
    op.drop_index('ix_core_items_source_conversation', table_name='items', schema='core')
    op.drop_index('ix_core_items_persona_id', table_name='items', schema='core')
    op.drop_index('ix_core_items_fecha', table_name='items', schema='core')
    op.drop_table('items', schema='core')
    op.drop_index('ix_core_personas_telefono', table_name='personas', schema='core')
    op.drop_index('ix_core_personas_email', table_name='personas', schema='core')
    op.drop_table('personas', schema='core')
    # ### end Alembic commands ###
